/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"

#include "bar_alpha.c"
#include "combo.c"
#include "bar_ltsymbol.c"
#include "bar_status.c"
#include "bar_statuscolors.c"
#include "bar_tags.c"
#include "bar_wintitle.c"

/* Other patches */
#include "autostart.c"
#include "cyclelayouts.c"
#include "focusdir.c"
#include "fullscreen.c"
#include "pertag.c"
#include "roundedcorners.c"
#include "scratchpad.c"
#include "stacker.c"
#include "sticky.c"
#include "swallow.c"
#include "transfer.c"
#include "vanitygaps.c"
#include "warp.c"
#include "xrdb.c"
/* Layouts */
#include "layout_facts.c"
#include "layout_centeredmaster.c"
#include "layout_fibonacci.c"
#include "layout_grid.c"
#include "layout_monocle.c"
#include "layout_tile.c"

